### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by camjac251** [Kasama/spicetify-jqbx#2]
Is this working for you still? I'm using the latest spicetify and spotify versions all installed with scoop (including this and the genius addon). I tried clean installing and it still creates the same issue. Genius will load after some time but JQBX never loads.

**Comment by topmillerm2** [comment]
just tried using this and I couldn't get it to work.  JQBX just doesn't load ever, just a white screen

**Comment by derekstephen** [comment]
I believe I've fixed the issue with the current pull request I've created. Feel free to test it!

**Comment by ghost** [comment]
> I believe I've fixed the issue with the current pull request I've created. Feel free to test it!

Doesn't seem to load for me, simply a blank screen

**Comment by PaulVerhoeven1** [comment]
i got the same problem! a blank screen that doesn't do anything.

**Comment by Kasama** [comment]
Hey! I'm sorry it has taken me this long, But I think I've fixed it now. The problem was that the bundle ID was set to `jqbx`, while the readme tells you to install the addon as `JQBX`. Both need to match. I've updated the readme to use `jqbx` as well.

Can any of you confirm that changing `JQBX` to `jqbx` in the folder name and `config.ini` fixes the issue?

**Comment by PaulVerhoeven1** [comment]
@Kasama That solved the problem for me, Thanks!

**Comment by topmillerm2** [comment]
@Kasama it's working on my end now 👍

**Comment by Kasama** [comment]
great to hear that!
